import 'package:flutter/material.dart';

List<String> url = [
  "https://g.page/AgaveKSA?share",
  "https://g.page/papayaksa?share",
  "https://g.page/Caffe_Aroma_ksa?share",
  "https://goo.gl/maps/CqDuoudCmArFimhU9",
  "https://goo.gl/maps/JQAcnMkUo1o4uH1X9",
  "https://goo.gl/maps/QfjhFZE9tnCPYwTXA",
  "https://goo.gl/maps/Rg5SmwWT9T9mN3DX8",
  "https://g.page/RedSeaMallKSA?share",
  "https://g.page/mallofarabia?share",
  "https://goo.gl/maps/jg68n6eUoXxjCZrx9",
  "https://goo.gl/maps/fV1C8q4FdosnuCcM6",
  "https://goo.gl/maps/eRyYHNNCo7Rd9zrh6",
  "https://goo.gl/maps/kGtmrGk6rJDRaZga6",
  "https://g.page/thuluth?share",
  "https://goo.gl/maps/7LVQvGYr8bkd9CbE7",
  "https://g.page/Caffeinelabsa?share",
  "https://g.page/sculpture-cafe?share",
  "https://goo.gl/maps/yoFtdMq1XhAMFLLcA",
  "https://goo.gl/maps/2wAwtPsCf5YAxCp5A",
  "https://goo.gl/maps/jn2SvJmwRmJ9Y5YcA",
  "https://goo.gl/maps/2ZoSNrg2KY9FFw7j8",
  "https://g.page/khayalrest?share",
  "https://goo.gl/maps/P7WxxLddY3BR6xiF9",
  "https://g.page/FogoJeddah?share",
  "https://g.page/MirageHotelJeddah?share",
  "https://goo.gl/maps/qgMNr7RJMXRxWkLp6",
  "   ",
  "https://g.page/cpjeddah?share",
  "https://g.page/tajjeddah?share",
  "https://goo.gl/maps/MddzBKhMYXbMA1Kc7",
  "https://goo.gl/maps/gZT1wtLZqMDQeuUY9",
  "https://g.page/movenpick-jeddah-al-nawras?share",
  "https://g.page/adel8?share",
  "https://goo.gl/maps/7ezxEK4nUJ4d45kk6",
  "https://goo.gl/maps/boEZDsnerz8zbATy9",
  "https://goo.gl/maps/4va2v5kuS8kwrwpm8",
  "https://g.page/LeConcheur?share",
  "https://g.page/tamees?share",
  "https://goo.gl/maps/6kSpF2pNHJBjhNxT8",
  "https://g.page/stita?share",
  "https://g.page/noveljeddah?share",
  "https://g.page/makanzamancafe?share",
  "https://goo.gl/maps/4FKQPuJNdq8tfejPA",
  "https://goo.gl/maps/kYoCtoeHAMyyXnH26",
  "https://g.page/angelscafesa?share",
  "https://goo.gl/maps/gUNqUvbTWd5R6fyPA",
  "https://g.page/gamba_ksa?share",
  "https://g.page/karatoon?share",
  "https://goo.gl/maps/tNVsaXfkKEq33Gxg7",
  "https://g.page/ketchup_ksa?share",
  "https://g.page/Alqalzamsultan?share",
  "https://goo.gl/maps/jULnDYQZQHJJ6gVU7",
  "https://goo.gl/maps/cvaN7Hd9fnocoh177",
  "https://goo.gl/maps/Kg1WAromrdyPJcHj7",
  "https://goo.gl/maps/Wj4Bmb52ydoYeDTMA",
  "https://goo.gl/maps/bsW4APAFyqgxnWcM6",
  "https://goo.gl/maps/ZbZ55jEcuHkeT9EV7",
  "https://goo.gl/maps/9jENKCc29a2ZxJ8V7",
  "https://goo.gl/maps/jRM8iTqTVwKhsQzs9",
  "https://g.page/naxosbaybeach?share",
  "https://g.page/ODreamBeach?share",
  "https://goo.gl/maps/3DX5j8kzi4hsLjzV6",
  "https://goo.gl/maps/DoNC5377rgcXsmHf9",
  "https://goo.gl/maps/vACRXgbLLBhJMJfq8",
];

List<String> nameIfon = [
  "   مطعم أقافي",
  "مطعم بابايا ",
  "اروما كافيية ومطعم",
  "تشيكي تشيز (ملاهي للاطفال)",
  "مطعم وكافي بلو اويشن",
  "فقية اكواريم",
  "الواجهة البحرية",
  "ردسي مول ",
  "العرب مول ",
  "ملاهي الشلال",
  "ملاهي الارض السعيدة",
  "البلد القديمة",
  "مطعم اكس تريب",
  "كوفي ثلث",
  "هايد اوت",
  "كافين لاب",
  "كوفي سكلبتشر",
  "كوب وكنبه",
  "انجلينا ",
  "كومار",
  "ميز",
  "مطعم خيال",
  "عزيز مول ",
  "مطعم فوغودي تشار",
  "Mirage Hotel",
  "فندق الدار البيضاء جراند جده ,",
  "فندق دار السلام ",
  "فندق كروان بلازا",
  "فندق تاج جده",
  "الواجهة البحريه",
  "روائع المكتبات ",
  "منتجع موفنبيك ",
  "ملاهي سماش ",
  "موفي سينما عزيز مول",
  "متحف مدينة الطيبات العالية",
  "حديقة الفيحاء",
  "لوكنشير ",
  "تميس٩",
  "I'm hungry",
  "مطعم ستيتة",
  "نوفل ",
  "مكان زمان",
  "بيت ورد",
  "مدينة الملك عبدالله ",
  "انجليز",
  "سراوند",
  "جامبا ",
  "كراتون",
  "خطوة جمل",
  "كتشب",
  "القلزم",
  "الياسمين مول",
  " ازور",
  "هيفاء مول",
  "الأندلس مول",
  "السلام مول",
  "الجامعة بلازا ",
  "90.grams",
  "شاطئ رملة ",
  "Naxos",
  "Dream ocean",
  "Le pont lamitie ",
  "Queens",
  "كابانا",
];
